version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_admin_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - order_admin_network
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: order_admin_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: order_admin_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: order_admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - order_admin_network

  redis:
    image: redis:7-alpine
    container_name: order_admin_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - order_admin_network

  nginx:
    image: nginx:alpine
    container_name: order_admin_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - order_admin_network
    depends_on:
      - app

volumes:
  dbdata:
    driver: local

networks:
  order_admin_network:
    driver: bridge 